export {
  ALL_SLUGS_QUERY,
  FEATURED_POST_QUERY,
  FOOTER_QUERY,
  PAGED_POSTS_QUERY,
  POST_BY_SLUG_QUERY,
  POST_COUNT_QUERY,
  POSTS_BY_AUTHOR_QUERY,
  SITE_SETTINGS_QUERY,
  PRODUCT_BY_SLUG_QUERY,
  ALL_PRODUCT_SLUGS_QUERY,
} from '@/infrastructure/sanity/queries'
